import { Injectable, Inject } from "@nestjs/common";
import { ReviewsDbService } from "@/common/db-services/reviews-db.service";
import { CACHE_MANAGER } from "@nestjs/cache-manager";
import type { Cache } from "cache-manager";

@Injectable()
export class ReviewsService {
  constructor(
    private readonly reviewsDbService: ReviewsDbService,
    @Inject(CACHE_MANAGER) private cacheManager: Cache,
  ) {}

  async createReview(productId: number, userUid: string, rating: number, reviewText?: string) {
    const review = await this.reviewsDbService.createReview(productId, userUid, rating, reviewText);
    
    // Invalidate products cache since average rating changed
    // Since cache keys are now dynamically generated by URL, we reset the cache
    await this.cacheManager.clear();
    
    return review;
  }
}
